Repository rohitinu6/Stock-Price-Prediction, pull requests merged in 2024-10, with the labels that each got.

#26 CONTRIBUTING.md
  Contributing.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1

#31 Merge code_of_conduct.md
  code-of-conduct.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#24 Updated README.md
  README.md
  Stock_Price_Prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level1

#39 Lightgbm-and-catboost--model
  Stock_Price_Prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2

#44 Added Issue Template #36
  .github/ISSUE_TEMPLATE/bug_report.yml
  .github/ISSUE_TEMPLATE/feature_request.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2

#45 Added basic data analysis and visualization
  Python File/Stock_Price_Prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2

#51 Update README.md
  README.md
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#58 Resolved Conflicts
  .ipynb_checkpoints/Stock_Price_Prediction-checkpoint.ipynb
  .ipynb_checkpoints/Stock_prediction_Data_Analysis-checkpoint.ipynb
  Stock_Price_Prediction.ipynb
  Stock_prediction_Data_Analysis.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2

#61 Added SMA indicator
  Python File/Stock_Price_Prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#68 Updated stock_price_prediction
  Python File/Stock_Price_Prediction.ipynb
  Stock_Price_Prediction(Updated).ipynb
  Stock_Price_Prediction.ipynb
  Stock_prediction_Data_Analysis.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2

#78 UPDATE THE README
  InvestWise - Stock Prediction Model.png
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2

#89 Add GitHub Actions #53
  .github/PR_TEMPLATE.md
  .github/workflows/contributioncheck.yml
  .github/workflows/dependencies.yml
  .github/workflows/greetings.yml
Labels: good first issue, gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#86 Updated Graphs in Readme.md
  README.md
  images/085ee2d1-3544-4bed-a558-5b0b801e806b.jpeg
  images/6c9ebb5b-a8ed-44de-8842-bf8f5c25990f.jpeg
  images/f23e9194-72de-438d-bd69-744667680d3e.jpeg
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#90 indicator graph improved
  Python File/Stock_Price_Prediction_REMOTE_20502.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#85 Matched feature names in model prediction
  .ipynb_checkpoints/Stock_Price_Prediction-checkpoint.ipynb
  Stock_Price_Prediction.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#100 Created ARIMA model
  ARIMA/ARIMA_V2.ipynb
  ARIMA/README.md
  ARIMA/hybrid.ipynb
  requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#114 Convert categorical variables to numeric variables
  .ipynb_checkpoints/stock_market(complete)-checkpoint.ipynb
  candlestick_chart.html
  stock_market(complete).ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#97 Fixes #19 by Implemented Buy/Sell Recommendation System with K-Means Clustering and Silhouette Score Evaluation
  buy_sell_recommendation_system.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#81 Financial Environment Segmentation
  Financial Environment Segmentation/Financial Environment Segmentation.ipynb
  Financial Environment Segmentation/Financial Insights - Market Segmentation.png
  Financial Environment Segmentation/README.md
  Multi-Asset Portfolio Modeling/Multi-Asset Portfolio Modeling.ipynb
  Multi-Asset Portfolio Modeling/README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#120 Resolve Warning by Using Input Layer for Input Shape in Keras Sequential Model
  .ipynb_checkpoints/Stock_Price_Prediction-checkpoint.ipynb
  Stock_Price_Prediction.ipynb
Labels: level2

#119 Updated Stock_prediction_Data_Analysis.ipynb
  Stock_prediction_Data_Analysis.ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#127 included Volume Weighted Average Price (VWAP)
  VWAP_included_stock_price_prediction.ipynb
Labels: level2

#128 Market Trend Classification Model
  Market Trend Classification Model/Market Trend Classification Model.ipynb
  Market Trend Classification Model/MarketTrend Analytics - Classification Model.png
  Market Trend Classification Model/README.md
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#139 ADD TABLE OF CONTENT ON THE README FILE
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#136 optimized the code using intel ai analytics toolkit
  Intel_Optimized/ARIMA_V2.ipynb
  Intel_Optimized/Stock_Price_Prediction_1.ipynb
  Intel_Optimized/Stock_prediction_Data_Analysis.ipynb
  Intel_Optimized/buy_sell_recommendation_system.ipynb
  Intel_Optimized/hybrid.ipynb
  Intel_Optimized/readme.md
  Intel_Optimized/reduced_redundancy_stock_price_prediction.ipynb
  Intel_Optimized/requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#147 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#155 Github actions for more connectivity!
  .github/workflows/comment_open_close.yml
  .github/workflows/pr_merge_comment.yaml
  .github/workflows/pr_raise_checker.yml
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#148 Performed EDA: Handled Missing Values and Outliers in Stock Price Data
  .ipynb_checkpoints/stock_market(complete)-checkpoint.ipynb
  stock_market(complete).ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#105 requirements.txt
  requirements.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#151 Created a Web Page for predicting the stock price and also implemented concept of ensemble learning closes #132
  Contributing.md
  Stock_Price_Prediction(Updated).ipynb
  Updated_SBIN.csv
  main.py
  prediction.pkl
  requirements.txt
  static/css/home.css
  static/css/stock.css
  templates/home.html
  templates/stock.html
Labels: gssoc-ext, hacktoberfest-accepted, hacktoberfest

#170 Enhanced Footer with Social Links ON README
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#161 Create LICENSE. Fixes #157
  LICENSE
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#162 Automated project structure updation using github workflows, python scripts and action bot
  .github/scripts/update_structure.py
  .github/workflows/update-readme.yml
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest

#163 Stock recommendation added issues #131 Closes #131
  Stock_Recommendation.ipynb
  nifty_500.csv
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#181 Added Table to Display Repository Statistics in README.md
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#166 Added Issue labeler work flow
  .github/workflows/issue_labeler.yaml
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#182 ENHANCE AND STRUCTURE THE CONTRIBUTORS SECTION
  PROJECT_STRUCTURE.md
  README.md
  repo_structure.txt
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#190 Analysed data and created Dashboard using Tableau
  Data Analysis/SBI Stock Analysis .png
  Data Analysis/SBI Stock Analysis Updated.pptx
  Data Analysis/SBI Stock Analysis Updated.twbx
Labels: gssoc-ext, hacktoberfest-accepted, level3, hacktoberfest

#184 Enhance README by Adding GitHub Repository Statistics Section and Project Title GIF [Fixed #173]
  README.md
  images/Screenshot 2024-10-25 194943.png
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#198 Update Overview Section and Fix Image Visibility in Performance Metrics [Fixed #196]
  README.md
Labels: gssoc-ext, hacktoberfest-accepted, level1, hacktoberfest

#207 Resolved warning of non-finite test scores and input_shape usage in dense layer
  .ipynb_checkpoints/stock_market(complete)-checkpoint.ipynb
  PROJECT_STRUCTURE.md
  candlestick_chart.html
  repo_structure.txt
  stock_market(complete).ipynb
Labels: gssoc-ext, hacktoberfest-accepted, level2, hacktoberfest
